# Generated by Django 3.0.3 on 2020-03-01 12:15

from django.db import migrations, models
import utils.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('author', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=254)),
                ('edition', models.CharField(max_length=10)),
                ('publication_year', models.IntegerField(validators=[utils.validators.year_validator])),
                ('authors', models.ManyToManyField(related_name='books', to='author.Author')),
            ],
            options={
                'unique_together': {('name', 'edition')},
            },
        ),
    ]
