language: python

python:
  - "3.8"

branches:
  only:
    - master

install:
  - pip install -r requirements.txt

before_script:
  - cp .env.example .env
  - python manage.py migrate

script:
  -  python manage.py test
